/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lrlvxxyokajquyieshww"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxybHZ4eHlva2FqcXV5aWVzaHd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NzM5NzksImV4cCI6MjA3NDA0OTk3OX0.xKH-y-UZujjoz6MYqwVmF-eTLivvYDthBt43QVZ2oE4"